### ISSUE TITLE
File generation doesn't work

### ISSUE THREAD

**Issue by alexlafroscia** [pixelhandler/ember-cli-es5-shim#2]
I'm having trouble getting the generator to work.  Here's what happens:

```
$ ember generate ember-cli-es5-shim
version: 0.1.5
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  cached git://github.com/es-shims/es5-shim.git#4.0.5
Installed browser packages via Bower.
```

Any suggestions?

**Comment by pixelhandler** [comment]
@alexlafroscia I tried out a new project with ember-cli 0.1.5 and added the ember-cli-es5-shim with npm install. I did get the same error reported `The globPattern "undefined" did not match any files` however the generated did it's job. After the install `"ember-cli-es5-shim": "^0.1.0",` was added to package.json and `"es5-shim": "^4.0.5"` was added to bower.json (by using the generator `ember generate ember-cli-es5-shim`). I have no idea what the error is but I ran `ember build` and then inspected the dist/assets/vendor.js file and found that the build does include the shim file bower_components/es5-shim/es5-shim.js was included in the vendor.js file build with ember-cli's build pipeline. For example, I searched the vendor.js file in the dist directory for "Brings an environment as close to ECMAScript 5 compliance" which is a comment from the es5-shim.js file and found that vendor does include the comment. 

The error seems to be noise.

**Comment by alexlafroscia** [comment]
Alright, thanks for the update!

**Comment by trabus** [comment]
Sorry about this, it was [happening with any blueprint that didn't have files in it](https://github.com/ember-cli/ember-cli/issues/3142). 
The good news is, it was a benign warning, and didn't affect the install process. And the even better news is that it's gone as of ember-cli 0.1.13. 

Please feel free to close this issue.
